function changeClass(){$(".switcher div").removeClass("selected"),$(this).addClass("selected")}function slidebarCanvas(){$("body").removeClass("off-canvas-sidebar-open")}$("#exampleInputPhone").mask("+7 (999) 999 - 99 - 99",{}),$("#AppPhone").mask("+7 (999) 999 - 99 - 99",{}),$("#request-phone").mask("+7 (999) 999 - 99 - 99",{}),$("#passport_series").mask("9999",{}),$("#wu_series").mask("9999",{}),$("#wu_number").mask("999999",{}),$("#passport_number").mask("999999",{}),$(".type-year").mask("9999",{}),$(".type-date").mask("99.99.9999",{}),$(".type-phone").mask("+7 (999) 999 - 99 - 99",{}),$(document).ready(function(){$(".owl-carousel.advantages").owlCarousel({margin:30,dots:!1,nav:!0,loop:!0,responsive:{0:{items:1},768:{items:2},1000:{items:4}}})}),$(".owl-carousel.category-car").owlCarousel({margin:30,nav:!0,loop:!0,responsive:{0:{items:1},768:{items:5},1000:{items:5}}}),$('.owl-carousel.category-car').each(function(index){$(this).find('.owl-nav, .owl-dots').wrapAll("<div class='owl-controls'></div>")}),$(".owl-carousel.contact-office").owlCarousel({margin:30,stagePadding:0,nav:!0,loop:!0,responsive:{0:{items:1},768:{items:2},1000:{items:3}}}),$('.owl-carousel.contact-office').each(function(index){$(this).find('.owl-nav, .owl-dots').wrapAll("<div class='owl-controls'></div>")}),jQuery(function(e){var a,t;a=e("[data-show]"),(t=e(".switch-js")).children().not(":first").hide(),a.click(function(){var a;a='[data-switch="'+e(this).data("show")+'"]',t.children(a).show(),t.children().not(a).hide()})}),$(document).ready(function(){$(".switcher div").on("click",changeClass)}),
/*$(document).ready(function(){$(".switcher li").on("click",changeClass), $('.switcher').on("mousewheel", function(e, delta) {this.scrollLeft -= (delta * 40),e.preventDefault();})}),*/
$(document).ready(function(){$("#menu-header-animate").on("click","a",function(e){e.preventDefault();var a=$(this).attr("href"),t=$(a).offset().top-60;$("body,html").animate({scrollTop:t},500)}),$("#menu-footer-animate").on("click","a",function(e){e.preventDefault();var a=$(this).attr("href"),t=$(a).offset().top-60;$("body,html").animate({scrollTop:t},500)}),$("#menu-slidebar-animate").on("click","a",function(e){e.preventDefault();var a=$(this).attr("href"),t=$(a).offset().top-60;$("body,html").animate({scrollTop:t},500)})}),jQuery.validator.addMethod("lettersonly", function(value, element){return this.optional(element) || /^[а-яА-ЯёЁ ]+$/i.test(value);}, "Допустимы только буквы и пробелы"),$(function(){$("#requestСheckbox").on("change",function(){$("#requestСheckbox").prop("checked")?$("#requestSubmit").attr("disabled",!1):$("#requestSubmit").attr("disabled",!0)})}),$(function(){$("#requestForm").validate({ignore:":disabled",rules:{"requestСheckbox":{required:!0},requestInputName:{required:!0,lettersonly: true,minlength:2,maxlength:40},requestInputPhone:{required:!0}},messages:{requestInputName:{required:"Поле обязательно для заполнения",minlength: jQuery.format("Слишком короткое имя"),maxlength:jQuery.format("Слишком длинное имя"),lettersonly:jQuery.format("Введены недопустимые символы")},requestInputPhone:{required:"Поле обязательно для заполнения"}}})}),$(function(){$("#callСheckbox").on("change",function(){$("#callСheckbox").prop("checked")?$("#callSubmit").attr("disabled",!1):$("#callSubmit").attr("disabled",!0)})}),$(function(){$("#callForm").validate({ignore:":disabled",rules:{"callСheckbox":{required:!0},callInputName:{required:!0,lettersonly: true,minlength:2,maxlength:40},callInputPhone:{required:!0}},messages:{callInputName:{required:"Поле обязательно для заполнения",minlength: jQuery.format("Слишком короткое имя"),maxlength:jQuery.format("Слишком длинное имя"),lettersonly:jQuery.format("Введены недопустимые символы")},callInputPhone:{required:"Поле обязательно для заполнения"}}})}),$(function(){$("#exampleСheckbox").on("change",function(){$("#exampleСheckbox").prop("checked")?$("#exampleSubmit").attr("disabled",!1):$("#exampleSubmit").attr("disabled",!0)})}),$(function(){$("#ApplicationForm").validate({ignore:":disabled",rules:{"exampleСheckbox":{required:!0},exampleInputName:{required:!0,lettersonly: true,minlength:2,maxlength:40},exampleInputPhone:{required:!0}},messages:{exampleInputName:{required:"Поле обязательно для заполнения",minlength: jQuery.format("Слишком короткое имя"),maxlength:jQuery.format("Слишком длинное имя"),lettersonly:jQuery.format("Введены недопустимые символы")},exampleInputPhone:{required:"Поле обязательно для заполнения"}}})});


/*$(document).ready(function () {
	$('.switcher').on("mousewheel", function(e, delta) {
        this.scrollLeft -= (delta * 40);
        e.preventDefault();
    });
    
    });*/
